### PR TITLE
Implement subidentities

### PR DESCRIPTION
**Pull request by Koochr**
The first draft of the subidentities functionality. Adding and getting subidentities works, however, this implementation doesn't allow multi-level subidentities. Some questions I have:
- It was described in the jira task to create a mapping between identities and subidentities, but the getter method is `getSubidentityByOwner`. Isn't it more reasonable to get subidentities by identity and not by owner?
- Regarding multi-level subidentities, the possible solution would be to add subidentities of all levels to the root identity (so keep it as it's implemented here), and also create keys in `ikv`, e.g.:  ```{"foo": {subidentities: ["bar"]}, "foo.bar": {subidentities: ["baz"]}}```
- The latter will require modification of `onlyIdendityDeployer` method, so it will split identity by `.` and check only the root part. Not sure it's the best way though.

### CODE REVIEW

**Comment by sergevar** [comment]
> It was described in the jira task to create a mapping between identities and subidentities, but the getter method is getSubidentityByOwner. Isn't it more reasonable to get subidentities by identity and not by owner?

Indeed, we should be able to query all subidentities by identity handle, irregardless of who's owning the main identity right now.

> Regarding multi-level subidentities, the possible solution would be to add subidentities of all levels to the root identity (so keep it as it's implemented here), and also create keys in ikv, e.g.: {"foo": {subidentities: ["bar"]}, "foo.bar": {subidentities: ["baz"]}}

Why wouldn't it work out of the box? Please test this scenario:
- try doing `registerSubidentity('level1', 'mainhandle')`
- and then `registerSubidentity('level2', 'level1.mainhandle')`
Everything else should theoretically work, including ikv and ownership checks

**Comment by tankakatan** [comment]
> Indeed, we should be able to query all subidentities by identity handle, irregardless of who's owning the main identity right now.

We need to be able to get all the owner sub-identities as well. We are going to display them in the `my identities` tab of point explorer.

So I think we should have both methods.

**Comment by tankakatan** [comment]
> > Indeed, we should be able to query all subidentities by identity handle, irregardless of who's owning the main identity right now.
> 
> We need to be able to get all the owner sub-identities as well. We are going to display them in the `my identities` tab of point explorer.
> 
> So I think we should have both methods.

@sergevar also it is not clear what exactly do you mean by `handle`. Please take a look at the `registerSubidentity` interface. The first two parameters there are `subhandle` and `handle`, right?

So in case of multi-level sub-handle we would want to call the method like this:
```
registerSubidentity('foo', 'bar.baz', ....);
```

Now what should be stored in `subidentitiesByHandle`? Should it be `subidentitiesByHandle['baz'].push('foo.bar')` or `subidentitiesByHandle['bar.baz'].push('foo')`?

In the first case it is problematic, because we'll have to parse the string in order to extract the root handle. In the second case it will be problematic to get all the sub-handles of the root handle, because they will be stored under multiple different keys.

Associating sub-handles with owner address doesn't seem to have this problem.

Please correct me if I'm wrong.

**Comment by sergevar** [comment]
> it is not clear what exactly do you mean by handle

I use "[sub]handle", "[sub]domain" and "[sub]identity" interchangeably in this context.

> We need to be able to get all the owner sub-identities as well. We are going to display them in the my identities tab of point explorer. So I think we should have both methods.

Normally, there must only be one pubkey/owner attached to one identity, a unique pairing rule. It's a soft requirement, and we sometimes have several identities attached to one key for our development needs, but it's not supposed to be like that. That's why `identityByOwner` returns only one value, not an array of identities owned.

With subidentities implemented, we broke this rule yet again, because we allow only the current owner to register a subidentity, which will assign the same owner to this subidentity. But because it doesn't break anything, it's fine. Although the ideal way, in the future, would be to then transfer the subidentity to some new pubkey, perhaps derived via HDWallets, so that the unique pairing requirement is upheld.

> So in case of multi-level sub-handle we would want to call the method like this:
> registerSubidentity('foo', 'bar.baz', ....);
> Now what should be stored in subidentitiesByHandle? Should it be subidentitiesByHandle['baz'].push('foo.bar') or subidentitiesByHandle['bar.baz'].push('foo')?

The latter, `subidentities['bar.baz'].push('foo')`

The trick allowing multi-level subidentities work out-of-the-box is that the rest of the code (ikv, registration, etc.) treats the current level like a normal identity, even if it's a subidentity (contains a dot in it).

> We are going to display them in the my identities tab of point explorer

This is tricky, but only if we break the unique pairing rule. Otherwise, we just use `identityByOwner` (which will return a subdomain if this is the only thing attached to this owner's pubkey). We can also check all subidentities, because by default they would be owned by the same owner. And then the rest is delegation, whatever handles this pubkey is allowed to deploy to.

-----------------

Actionable:

- Instead of `subidentityByOwner` we should just have `getSubidentity(identity, index)` to allow us to iterate over subidentities

**Comment by Koochr** [comment]
> Why wouldn't it work out of the box? Please test this scenario:
>
> try doing registerSubidentity('level1', 'mainhandle')
> and then registerSubidentity('level2', 'level1.mainhandle')
> Everything else should theoretically work, including ikv and ownership checks

There are 2 problems with it. First, dot is not allowed, but it's easy to fix.
Second, in this example, 'level1.mainhandle' will not pass the ownership check

Btw, I've just realized, that the comment from the task
```
// note: only validating subhandle, because handle was validated at creation,
// and non-existing handles would not pass the ownership check
_validateIdentity(subhandle, identityOwner, false, true);
```
is not true. In my current implementation, we don't check for ownership of the root handle. This should be fixed, of course, but for your example, we'll need to split string by `.`, find the root handle and check it explicitly

**Comment by sergevar** [comment]
> First, dot is not allowed, but it's easy to fix.

Dot is not allowed in `subhandle` argument of `registerSubidentity`, because only that one is being sent to `_validateIdentity`. `handle` is not checked for alphanumericity, so you can pass anything there, as long as you already own it.

> Second, in this example, 'level1.mainhandle' will not pass the ownership check

Yes, you need to register 'level1.mainhandle' first. By this, you become the owner of it, and can register 'level2' then.

> In my current implementation, we don't check for ownership of the root handle

We check by using the modifier `onlyIdentityOwner(handle)`. It makes sure that you really own whatever is passed as `handle`, be it an identity or a subidentity.

**Comment by diogosmendonca** [comment]
@Koochr great work, especially for a first time with solidity. Looks good for me assuming that the owner of the identity will be the owner of all subidentities. Without this assumption, we could need some changes in checking the deployers and owners. One thing that I noticed is that is not possible to list all subidentities of an identity without using events and there is no way to deactivate a subidentity. Those requirements may be needed in the future to manage subidentities. Let me know if any other help is needed, maybe I could help during integration tests with deployment process and running DApps on subidentities.

**Comment by sergevar** [comment]
Please revert to the previous implementation of registering subidentities, utilizing _selfReg, otherwise a lot of things like ikv will be broken

One edge case we need to fix for: if the owner already has an identity attached, don't change it (i.e. if you register an identity and several subidentities, `identityByOwner` should return the first one, not the last one)

You can ping me or @tankakatan on details

**Review by jensendarren — APPROVED** [review]

**Pull request merged**
