### PR TITLE
Rewrite identity migration script

### PR DESCRIPTION
**Pull request by Koochr**

### CODE REVIEW

**Comment by dsm-w3f** [comment]
@Koochr I'm getting those errors during the compilation of the project `npm run build`. Any clue?  My tsc version installed is 3.8.3. I'm running on Linux.

```
npm run build

> @pointnetwork/point-contracts@0.1.1 build
> tsc

tasks/importer/identityTasks/downloadData.ts:1:26 - error TS2307: Cannot find module '../../../typechain' or its corresponding type declarations.

1 import { Identity } from '../../../typechain';
                           ~~~~~~~~~~~~~~~~~~~~

tasks/importer/identityTasks/downloadData.ts:35:46 - error TS7006: Parameter 'e' implicitly has an 'any' type.

35       `Found ${identityCreatedEvents.filter((e) => !!e.args).length} identities`
                                                ~

tasks/importer/identityTasks/downloadData.ts:40:18 - error TS7006: Parameter 'e' implicitly has an 'any' type.

40         .filter((e) => !!e.args)
                    ~

tasks/importer/identityTasks/downloadData.ts:41:15 - error TS7006: Parameter 'e' implicitly has an 'any' type.

41         .map((e) => {
                 ~

tasks/importer/identityTasks/downloadData.ts:61:47 - error TS7006: Parameter 'e' implicitly has an 'any' type.

61     console.log(`Found ${ikvSetEvents.filter((e) => !!e.args).length} ikv`);
                                                 ~

tasks/importer/identityTasks/downloadData.ts:65:18 - error TS7006: Parameter 'e' implicitly has an 'any' type.

65         .filter((e) => !!e.args)
                    ~

tasks/importer/identityTasks/downloadData.ts:66:15 - error TS7006: Parameter 'e' implicitly has an 'any' type.

66         .map((e) => {
                 ~

tasks/importer/identityTasks/uploadData.ts:2:26 - error TS2307: Cannot find module '../../../typechain' or its corresponding type declarations.

2 import { Identity } from '../../../typechain';
                           ~~~~~~~~~~~~~~~~~~~~


Found 8 errors in 2 files.

Errors  Files
     7  tasks/importer/identityTasks/downloadData.ts:1
     1  tasks/importer/identityTasks/uploadData.ts:2
```

**Comment by michelnapo** [comment]
@Koochr I'm getting those errors during the project compilation `npm run build`. Any clue? My tsc verstion is 3.8.3. I'm running on Linux:

```
npm run build

> @pointnetwork/point-contracts@0.1.1 build
> tsc

tasks/importer/identityTasks/downloadData.ts:1:26 - error TS2307: Cannot find module '../../../typechain' or its corresponding type declarations.

1 import { Identity } from '../../../typechain';
                           ~~~~~~~~~~~~~~~~~~~~

tasks/importer/identityTasks/downloadData.ts:35:46 - error TS7006: Parameter 'e' implicitly has an 'any' type.

35       `Found ${identityCreatedEvents.filter((e) => !!e.args).length} identities`
                                                ~

tasks/importer/identityTasks/downloadData.ts:40:18 - error TS7006: Parameter 'e' implicitly has an 'any' type.

40         .filter((e) => !!e.args)
                    ~

tasks/importer/identityTasks/downloadData.ts:41:15 - error TS7006: Parameter 'e' implicitly has an 'any' type.

41         .map((e) => {
                 ~

tasks/importer/identityTasks/downloadData.ts:61:47 - error TS7006: Parameter 'e' implicitly has an 'any' type.

61     console.log(`Found ${ikvSetEvents.filter((e) => !!e.args).length} ikv`);
                                                 ~

tasks/importer/identityTasks/downloadData.ts:65:18 - error TS7006: Parameter 'e' implicitly has an 'any' type.

65         .filter((e) => !!e.args)
                    ~

tasks/importer/identityTasks/downloadData.ts:66:15 - error TS7006: Parameter 'e' implicitly has an 'any' type.

66         .map((e) => {
                 ~

tasks/importer/identityTasks/uploadData.ts:2:26 - error TS2307: Cannot find module '../../../typechain' or its corresponding type declarations.

2 import { Identity } from '../../../typechain';
                           ~~~~~~~~~~~~~~~~~~~~


Found 8 errors in 2 files.

Errors  Files
     7  tasks/importer/identityTasks/downloadData.ts:1
     1  tasks/importer/identityTasks/uploadData.ts:2
```

**Comment by Koochr** [comment]
@michelnapo try first running `npx hardhat compile`

**Comment by michelnapo** [comment]
@Koochr  still having error when I ran `npx hardhat compile`:

```
npx hardhat compile
An unexpected error occurred:

tasks/importer/identityTasks/downloadData.ts:1:26 - error TS2307: Cannot find module '../../../typechain' or its corresponding type declarations.

1 import { Identity } from '../../../typechain';
                           ~~~~~~~~~~~~~~~~~~~~
tasks/importer/identityTasks/downloadData.ts:35:46 - error TS7006: Parameter 'e' implicitly has an 'any' type.

35       `Found ${identityCreatedEvents.filter((e) => !!e.args).length} identities`
                                                ~
tasks/importer/identityTasks/downloadData.ts:40:18 - error TS7006: Parameter 'e' implicitly has an 'any' type.

40         .filter((e) => !!e.args)
                    ~
tasks/importer/identityTasks/downloadData.ts:41:15 - error TS7006: Parameter 'e' implicitly has an 'any' type.

41         .map((e) => {
                 ~
tasks/importer/identityTasks/downloadData.ts:61:47 - error TS7006: Parameter 'e' implicitly has an 'any' type.

61     console.log(`Found ${ikvSetEvents.filter((e) => !!e.args).length} ikv`);
                                                 ~
tasks/importer/identityTasks/downloadData.ts:65:18 - error TS7006: Parameter 'e' implicitly has an 'any' type.

65         .filter((e) => !!e.args)
                    ~
tasks/importer/identityTasks/downloadData.ts:66:15 - error TS7006: Parameter 'e' implicitly has an 'any' type.

66         .map((e) => {
```

**Review by michelnapo — APPROVED** [review]
@amherag and @jensendarren now the expected time to the script run with 10000 identities is from 2 to 3 hours. Please check in uranus testnet.

**Review by amherag — APPROVED** [review]

**Pull request merged**
